name: Python Library Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install wheel twine

    - name: Read current version
      id: version
      run: echo "::set-output name=version::$(grep -oP '(?<=version=\")[^\"]*' setup.py)"

    - name: Increment version
      id: new_version
      run: echo "::set-output name=new_version::${{ steps.version.outputs.version | awk -F. -v OFS=. '{$NF++;print}' }}"

    - name: Update version in setup.py
      run: sed -i "s/version='${{ steps.version.outputs.version }}'/version='${{ steps.new_version.outputs.new_version }}'/" setup.py

    - name: Build distribution package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Publish to PyPI
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
