on:
  push:
    branches:
      - main

jobs:
  set_current_directory:
    runs-on: ubuntu-latest
    outputs:
      id: current_directory
    steps:
      - name: Check setup.py existence
        run: |
          if [ -f "workflowStuff/setup.py" ]; then
            echo "::set-output name=current_directory::$(pwd)/workflowStuff"
          else
            echo "Error: setup.py not found in workflowStuff directory."
            echo "Current directory contents:"
            ls -R
            echo "workflowStuff directory contents:"
            ls -R workflowStuff
            exit 1
          fi

  checkout:
    runs-on: ubuntu-latest
    needs: set_current_directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

  # Rest of the workflow...
